### PR TITLE
Added feature to add all modified files before committing changes.

### PR DESCRIPTION
**Pull request by takuya-o**
There is an addAllChangeBeforeCommit setting in config.js, but it had no effect, so I added it to the code.

### CODE REVIEW

**Comment by shanginn** [comment]
hey there! thanks for noticing
I was using `git add --all` for that, maybe it will give the same effect?

**Comment by shanginn** [comment]
ok, it is not the same.

But the purpose of `addAllChangesBeforeCommit` was to run a single command to add all files and push.

I later discarded that idea in favor of simple alias: `alias gai="git add --all && git-aicommit && git push"`

Do you still think such feature could be useful?

**Comment by takuya-o** [comment]
> I was using `git add --all` for that, maybe it will give the same effect?

This corresponds to "git add --update". This differs from "git -all" in that it does not add new files.
I like to use "git add --update" because I often make the mistake of adding a garbage file that is thrown out due to a failed redirect.

I made this pull request because the option wasn't implemented, so if you don't want the option, we don't need this patch.

**Comment by shanginn** [comment]
I have to use for it. I can add it, if you find it useful, otherwise it better to just remove the option from the config :)

**Comment by shanginn** [comment]
removed in 5.2.0

**Pull request closed without merging**
